version: "3.7"

services:
  mongo:
    container_name: mongo
    image: mongo:4-xenial
    ports:
      - 27017:27017
    networks:
      - java_network
  redis:
    container_name: redis
    image: redis-5
    networks:
      - java_network
    ports:
      - 27017:27017
  java-docker:
    container_name: java-docker
    image: java-docker:1.0
    ports:
      - 8080:8080
    networks:
      - java_network
    depends_on:
      - redis
      - mongo
    environment:
      - NAME=docker
      - MONGO_HOST=mongo
      - MONGO_PORT=27016
      - REDIS_PORT=6379

networks:
  java_network:
    name: java_network